@Hydra.Api_HostAddress = http://localhost:5088
@token = pega_aqui_el_token

GET {{Hydra.Api_HostAddress}}/api/v1/tenants
Accept: application/json

###

POST {{Hydra.Api_HostAddress}}/api/v1/tenants
Content-Type: application/json

{
  "nombreTenant": "Manhattan Trust Bank",
  "correo": "admin@manhattan.test",
  "password": "Admin123"
}

###

POST {{Hydra.Api_HostAddress}}/api/v1/auth/register
Content-Type: application/json

{
  "tenantSlug": "manhattan-trust",
  "fullName": "Cliente Uno",
  "documentNumber": "123456789",
  "email": "cliente@manhattan.test",
  "password": "Client123"
}

###

POST {{Hydra.Api_HostAddress}}/api/v1/auth/login
Content-Type: application/json

{
  "tenantSlug": "manhattan-trust",
  "email": "cliente@manhattan.test",
  "password": "Client123"
}

###

GET {{Hydra.Api_HostAddress}}/api/v1/auth/me
Accept: application/json
Authorization: Bearer {{token}}

###

POST {{Hydra.Api_HostAddress}}/api/v1/auth/logout
Accept: application/json
Authorization: Bearer {{token}}

###

POST {{Hydra.Api_HostAddress}}/api/v1/accounts/recharge
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "amount": 50000
}
