CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260610014410_InitialCreate') THEN
    CREATE TYPE account_status AS ENUM ('ACTIVE', 'INACTIVE', 'BLOCKED');
    CREATE TYPE fee_type_enum AS ENUM ('FIXED', 'PERCENTAGE');
    CREATE TYPE idempotency_state AS ENUM ('PROCESSING', 'COMPLETED');
    CREATE TYPE transaction_status AS ENUM ('PENDING', 'SUCCESS', 'FAILED');
    CREATE TYPE transaction_type AS ENUM ('DEPOSIT', 'WITHDRAW', 'TRANSFER');
    CREATE TYPE user_role AS ENUM ('ADMIN', 'CLIENT');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260610014410_InitialCreate') THEN
    CREATE TABLE "AspNetRoles" (
        "Id" text NOT NULL,
        "Name" character varying(256),
        "NormalizedName" character varying(256),
        "ConcurrencyStamp" text,
        CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260610014410_InitialCreate') THEN
    CREATE TABLE "AspNetUsers" (
        "Id" text NOT NULL,
        "UserName" character varying(256),
        "NormalizedUserName" character varying(256),
        "Email" character varying(256),
        "NormalizedEmail" character varying(256),
        "EmailConfirmed" boolean NOT NULL,
        "PasswordHash" text,
        "SecurityStamp" text,
        "ConcurrencyStamp" text,
        "PhoneNumber" text,
        "PhoneNumberConfirmed" boolean NOT NULL,
        "TwoFactorEnabled" boolean NOT NULL,
        "LockoutEnd" timestamp with time zone,
        "LockoutEnabled" boolean NOT NULL,
        "AccessFailedCount" integer NOT NULL,
        CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260610014410_InitialCreate') THEN
    CREATE TABLE tenants (
        id uuid NOT NULL,
        name character varying(100) NOT NULL,
        slug character varying(50) NOT NULL,
        main_currency character varying(3) NOT NULL,
        max_transaction_amount numeric(18,2) NOT NULL,
        fee_type fee_type_enum NOT NULL,
        fee_value numeric(18,4) NOT NULL,
        webhook_url text,
        created_at timestamp with time zone NOT NULL DEFAULT (now()),
        updated_at timestamp with time zone NOT NULL DEFAULT (now()),
        CONSTRAINT tenants_pkey PRIMARY KEY (id),
        CONSTRAINT chk_fee_value CHECK (fee_value >= 0),
        CONSTRAINT chk_max_amount CHECK (max_transaction_amount > 0),
        CONSTRAINT chk_percentage_limit CHECK (fee_type <> 'PERCENTAGE' OR fee_value <= 100),
        CONSTRAINT chk_tenant_main_currency CHECK (main_currency ~ '^[A-Z]{3}$')
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260610014410_InitialCreate') THEN
    CREATE TABLE "AspNetRoleClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoleId" text NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260610014410_InitialCreate') THEN
    CREATE TABLE "AspNetUserClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" text NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260610014410_InitialCreate') THEN
    CREATE TABLE "AspNetUserLogins" (
        "LoginProvider" text NOT NULL,
        "ProviderKey" text NOT NULL,
        "ProviderDisplayName" text,
        "UserId" text NOT NULL,
        CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
        CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260610014410_InitialCreate') THEN
    CREATE TABLE "AspNetUserRoles" (
        "UserId" text NOT NULL,
        "RoleId" text NOT NULL,
        CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
        CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260610014410_InitialCreate') THEN
    CREATE TABLE "AspNetUserTokens" (
        "UserId" text NOT NULL,
        "LoginProvider" text NOT NULL,
        "Name" text NOT NULL,
        "Value" text,
        CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
        CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260610014410_InitialCreate') THEN
    CREATE TABLE exchange_rates (
        id uuid NOT NULL,
        tenant_id uuid NOT NULL,
        from_currency character varying(3) NOT NULL,
        to_currency character varying(3) NOT NULL,
        rate numeric(18,8) NOT NULL,
        created_at timestamp with time zone NOT NULL DEFAULT (now()),
        CONSTRAINT exchange_rates_pkey PRIMARY KEY (id),
        CONSTRAINT chk_er_from CHECK (from_currency ~ '^[A-Z]{3}$'),
        CONSTRAINT chk_er_to CHECK (to_currency ~ '^[A-Z]{3}$'),
        CONSTRAINT chk_exchange_different_currency CHECK (from_currency <> to_currency),
        CONSTRAINT chk_exchange_rate_positive CHECK (rate > 0),
        CONSTRAINT exchange_rates_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260610014410_InitialCreate') THEN
    CREATE TABLE users (
        id uuid NOT NULL,
        tenant_id uuid NOT NULL,
        full_name character varying(150) NOT NULL,
        email character varying(150) NOT NULL,
        password_hash text NOT NULL,
        role user_role NOT NULL,
        created_at timestamp with time zone NOT NULL DEFAULT (now()),
        updated_at timestamp with time zone NOT NULL DEFAULT (now()),
        CONSTRAINT users_pkey PRIMARY KEY (id),
        CONSTRAINT "AK_users_tenant_id_id" UNIQUE (tenant_id, id),
        CONSTRAINT users_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260610014410_InitialCreate') THEN
    CREATE TABLE accounts (
        id uuid NOT NULL,
        tenant_id uuid NOT NULL,
        owner_id uuid NOT NULL,
        account_number character varying(30) NOT NULL,
        balance numeric(18,2) NOT NULL,
        currency character varying(3) NOT NULL,
        status account_status NOT NULL DEFAULT ('ACTIVE'::account_status),
        created_at timestamp with time zone NOT NULL DEFAULT (now()),
        updated_at timestamp with time zone NOT NULL DEFAULT (now()),
        deactivated_at timestamp with time zone,
        CONSTRAINT accounts_pkey PRIMARY KEY (id),
        CONSTRAINT "AK_accounts_tenant_id_id" UNIQUE (tenant_id, id),
        CONSTRAINT chk_account_balance_positive CHECK (balance >= 0),
        CONSTRAINT chk_account_currency CHECK (currency ~ '^[A-Z]{3}$'),
        CONSTRAINT fk_accounts_owner_same_tenant FOREIGN KEY (tenant_id, owner_id) REFERENCES users (tenant_id, id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260610014410_InitialCreate') THEN
    CREATE TABLE audit_logs (
        id uuid NOT NULL,
        tenant_id uuid NOT NULL,
        user_id uuid NOT NULL,
        action character varying(100) NOT NULL,
        old_value jsonb,
        new_value jsonb,
        created_at timestamp with time zone NOT NULL DEFAULT (now()),
        CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
        CONSTRAINT fk_audit_user_same_tenant FOREIGN KEY (tenant_id, user_id) REFERENCES users (tenant_id, id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260610014410_InitialCreate') THEN
    CREATE TABLE idempotency_records (
        id uuid NOT NULL,
        tenant_id uuid NOT NULL,
        user_id uuid NOT NULL,
        idempotency_key uuid NOT NULL,
        request_hash text NOT NULL,
        response_body jsonb,
        status_code integer,
        state idempotency_state NOT NULL DEFAULT ('PROCESSING'::idempotency_state),
        created_at timestamp with time zone NOT NULL DEFAULT (now()),
        expires_at timestamp with time zone NOT NULL,
        CONSTRAINT idempotency_records_pkey PRIMARY KEY (id),
        CONSTRAINT chk_idempotency_expiration CHECK (expires_at > created_at),
        CONSTRAINT fk_idempotency_user_same_tenant FOREIGN KEY (tenant_id, user_id) REFERENCES users (tenant_id, id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260610014410_InitialCreate') THEN
    CREATE TABLE transactions (
        id uuid NOT NULL,
        tenant_id uuid NOT NULL,
        user_id uuid NOT NULL,
        type transaction_type NOT NULL,
        source_account_id uuid,
        destination_account_id uuid,
        original_amount numeric(18,2) NOT NULL,
        converted_amount numeric(18,2),
        exchange_rate numeric(18,8),
        fee_amount numeric(18,2) DEFAULT 0.0,
        status transaction_status NOT NULL DEFAULT ('PENDING'::transaction_status),
        idempotency_key uuid NOT NULL,
        correlation_id uuid NOT NULL,
        created_at timestamp with time zone NOT NULL DEFAULT (now()),
        CONSTRAINT transactions_pkey PRIMARY KEY (id),
        CONSTRAINT chk_trans_converted_amount_positive CHECK (converted_amount IS NULL OR converted_amount > 0),
        CONSTRAINT chk_trans_fee_positive CHECK (fee_amount >= 0),
        CONSTRAINT chk_trans_original_amount_positive CHECK (original_amount > 0),
        CONSTRAINT chk_transaction_account_shape CHECK ((type = 'DEPOSIT' AND source_account_id IS NULL AND destination_account_id IS NOT NULL)
    OR (type = 'WITHDRAW' AND source_account_id IS NOT NULL AND destination_account_id IS NULL)
    OR (type = 'TRANSFER' AND source_account_id IS NOT NULL AND destination_account_id IS NOT NULL AND source_account_id <> destination_account_id)),
        CONSTRAINT fk_transactions_destination_same_tenant FOREIGN KEY (tenant_id, destination_account_id) REFERENCES accounts (tenant_id, id) ON DELETE RESTRICT,
        CONSTRAINT fk_transactions_source_same_tenant FOREIGN KEY (tenant_id, source_account_id) REFERENCES accounts (tenant_id, id) ON DELETE RESTRICT,
        CONSTRAINT fk_transactions_user_same_tenant FOREIGN KEY (tenant_id, user_id) REFERENCES users (tenant_id, id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260610014410_InitialCreate') THEN
    CREATE UNIQUE INDEX idx_accounts_tenant_account_number ON accounts (tenant_id, account_number);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260610014410_InitialCreate') THEN
    CREATE INDEX idx_accounts_tenant_owner ON accounts (tenant_id, owner_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260610014410_InitialCreate') THEN
    CREATE UNIQUE INDEX uq_accounts_tenant_id_id ON accounts (tenant_id, id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260610014410_InitialCreate') THEN
    CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260610014410_InitialCreate') THEN
    CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260610014410_InitialCreate') THEN
    CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260610014410_InitialCreate') THEN
    CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260610014410_InitialCreate') THEN
    CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260610014410_InitialCreate') THEN
    CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260610014410_InitialCreate') THEN
    CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260610014410_InitialCreate') THEN
    CREATE INDEX idx_audit_tenant_date ON audit_logs (tenant_id, created_at DESC);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260610014410_InitialCreate') THEN
    CREATE INDEX "IX_audit_logs_tenant_id_user_id" ON audit_logs (tenant_id, user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260610014410_InitialCreate') THEN
    CREATE UNIQUE INDEX idx_exchange_rates_tenant_pair ON exchange_rates (tenant_id, from_currency, to_currency);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260610014410_InitialCreate') THEN
    CREATE UNIQUE INDEX idempotency_records_tenant_id_user_id_idempotency_key_key ON idempotency_records (tenant_id, user_id, idempotency_key);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260610014410_InitialCreate') THEN
    CREATE INDEX idx_idempotency_expiration ON idempotency_records (expires_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260610014410_InitialCreate') THEN
    CREATE INDEX idx_idempotency_key ON idempotency_records (idempotency_key);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260610014410_InitialCreate') THEN
    CREATE UNIQUE INDEX tenants_slug_key ON tenants (slug);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260610014410_InitialCreate') THEN
    CREATE INDEX idx_transactions_correlation ON transactions (correlation_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260610014410_InitialCreate') THEN
    CREATE INDEX idx_transactions_destination ON transactions (destination_account_id) WHERE (destination_account_id IS NOT NULL);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260610014410_InitialCreate') THEN
    CREATE INDEX idx_transactions_source ON transactions (source_account_id) WHERE (source_account_id IS NOT NULL);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260610014410_InitialCreate') THEN
    CREATE INDEX idx_transactions_tenant_date ON transactions (tenant_id, created_at DESC);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260610014410_InitialCreate') THEN
    CREATE INDEX idx_transactions_type ON transactions (type);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260610014410_InitialCreate') THEN
    CREATE INDEX "IX_transactions_tenant_id_destination_account_id" ON transactions (tenant_id, destination_account_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260610014410_InitialCreate') THEN
    CREATE INDEX "IX_transactions_tenant_id_source_account_id" ON transactions (tenant_id, source_account_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260610014410_InitialCreate') THEN
    CREATE INDEX "IX_transactions_tenant_id_user_id" ON transactions (tenant_id, user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260610014410_InitialCreate') THEN
    CREATE UNIQUE INDEX uq_transactions_tenant_id_id ON transactions (tenant_id, id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260610014410_InitialCreate') THEN
    CREATE UNIQUE INDEX uq_users_tenant_id_id ON users (tenant_id, id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260610014410_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260610014410_InitialCreate', '10.0.9');
    END IF;
END $EF$;
COMMIT;

