name: Deploy production

on:
  push:
    branches:
      - main

permissions:
  packages: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          IMAGE=ghcr.io/${{ github.repository }}:${{ github.sha }}

          docker build \
            -f Hydra.Api/Dockerfile \
            -t $IMAGE \
            .

      - name: Push Docker image
        run: |
          IMAGE=ghcr.io/${{ github.repository }}:${{ github.sha }}
          docker push $IMAGE

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 95.111.229.119
          username: root
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            set -e

            echo "🔐 Login GHCR"
            echo "${{ secrets.TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

            IMAGE=ghcr.io/${{ github.repository }}:${{ github.sha }}

            echo "📦 Pull image"
            docker pull $IMAGE

            echo "🛑 Stop old container"
            docker stop hydra-bank || true
            docker rm hydra-bank || true

            echo "🌐 Ensure docker network"
            docker network create hydra-net || true

            echo "🔌 Connect dependencies"
            docker network connect hydra-net redishydra || true
            docker network connect hydra-net postgreshydra || true

            echo "🚀 Run new container"
            docker run -d \
              --name hydra-bank \
              --restart always \
              --network hydra-net \
              -p 8092:8080 \
              -e Redis__Configuration="redishydra:6379,password=${{ secrets.REDIS_PASSWORD }}" \
              -e ConnectionStrings__Redis="redishydra:6379,password=${{ secrets.REDIS_PASSWORD }}" \
              -e ConnectionStrings__DefaultConnection="Host=postgreshydra;Port=5432;Database=DbHydra;Username=postgres;Password=password" \
              $IMAGE

            echo "🧹 Clean unused images"
            docker image prune -f

            echo "✅ Deploy completed"
